### ISSUE TITLE
Default key for powerdns

### ISSUE THREAD

**Issue by random-robbie** [Paradoxis/Flask-Unsign-Wordlist#2]
Default key seems to be missing for powerdns i thought might be in this word list.

`a-very-secret-key`

taken from https://github.com/ngoduykhanh/PowerDNS-Admin

Not sure how you are generating the wordlists from github but thought id submit this for you.

**Comment by Paradoxis** [comment]
Thanks for the suggestion, if it’s not already in there I’ll add it once I have time :)

The wordlists are generated by a script that scrapes GitHub and various other sources for secrets as described in my blog post, but just a slightly more advanced version of it that also auto-pushes them every week, so if you use them in your bug bounty software be sure to update it regularly for the best results
