### ISSUE TITLE
[Improvment] add secret keys

### ISSUE THREAD

**Issue by random-robbie** [Paradoxis/Flask-Unsign-Wordlist#3]
Hey,

Can you please add `thisISaSECRET_1234` it's inside the apache superset readme files.

Can you add `e951e5a1f4b94151b360f47edf596dd2` it's the default secret_key for powerdns.

**Comment by Paradoxis** [comment]
Sorry for not replying, this one slipped by me somehow :) Implemented it, in the future feel free to add a PR with new keys and I'll be sure to accept them
